### ISSUE TITLE
Database not connected?

### ISSUE THREAD

**Issue by rahulrk2303** [jayrajmulani/edu-setu#24]
Unable to register as a student or professor. It keeps loading. Please confirm is database is up and running.
![image](https://user-images.githubusercontent.com/30636208/200773647-5d6727ad-6472-4b15-96cb-e2e4afbba5cb.png)

**Comment by jayrajmulani** [comment]
Yes, Oracle free tier database shuts down automatically if it sits idle for a week. I just rebooted the DB instance on cloud. 
It should work okay now. Please join the [discord server ](https://discord.gg/ANGKkKvmWH) and we can work on getting you guys access to the cloud console.. 


![Oracle DB](https://user-images.githubusercontent.com/39649967/200913208-29218997-863a-42a4-a404-aef63c1750e2.png)
