### ISSUE TITLE
Add to Oracle DB

### ISSUE THREAD

**Issue by sbkrishna123** [jayrajmulani/edu-setu#25]
Hey @jayrajmulani, 
I'm Supriya Krishna from group 26. Can you please provide me and my team mates with access to Oracle DB so we can start working on the project.
Emails:
sbkrishn@ncsu.edu
esingha@ncsu.edu
garulse@ncsu.edu

Thanks.

**Comment by jayrajmulani** [comment]
Hey, 
I have created your users and added you to the necessary groups..
I sent an email - separately to each of you guys with the initial credentials. 
You should have administrator access to the software-engineering compartment.. 

Let me know if you face any issues.
