### ISSUE TITLE
Project / Research / TA RA Opportunity Backend

### ISSUE THREAD

**Issue by jayrajmulani** [jayrajmulani/edu-setu#4]
1. DB Design
2. APIs
3. Request / Response formats report

**Comment by jayrajmulani** [comment]
## APIs needed

1. `/register`
2. `/login`
3. `/add_posting`
4. `/get_specific_posting`
5. `/get_all_postings`
6. `/get_all_postings_by_professor`
7. `/add_application`
8. `/get_specific_application`
9. `/get_all_applications`
10. `/get_all_applications_by_student`
11. `/update_posting`
12. `/update_application`

**Comment by Yashasya** [comment]
All the API's are created and functional
